//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.04 at 01:49:42 PM EEST 
//


package gr.ntua.ivml.mint.rdf.edm.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * EuropeanaType contains the Europeana Properties.
 * 
 * <p>Java class for EuropeanaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EuropeanaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" type="{http://www.example.org/EDMSchemaV9}SimpleLiteral"/>
 *         &lt;element name="dataProvider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hasMet" type="{http://www.example.org/EDMSchemaV9}SimpleLiteral" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hasType" type="{http://www.example.org/EDMSchemaV9}SimpleLiteral" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.example.org/EDMSchemaV9}SimpleLiteral"/>
 *         &lt;element name="object" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="provider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rights" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.example.org/EDMSchemaV9}Edmtype"/>
 *         &lt;element name="unstored" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="uri" type="{http://www.example.org/EDMSchemaV9}SimpleLiteral" minOccurs="0"/>
 *         &lt;element name="userTag" type="{http://www.example.org/EDMSchemaV9}SimpleLiteral" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}date" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EuropeanaType", propOrder = {
    "country",
    "dataProvider",
    "hasMet",
    "hasType",
    "language",
    "object",
    "provider",
    "rights",
    "type",
    "unstored",
    "uri",
    "userTag",
    "year"
})
public class EuropeanaType {

    @XmlElement(required = true)
    protected SimpleLiteral country;
    protected String dataProvider;
    protected List<SimpleLiteral> hasMet;
    protected List<SimpleLiteral> hasType;
    @XmlElement(required = true)
    protected SimpleLiteral language;
    @XmlSchemaType(name = "anyURI")
    protected String object;
    @XmlElement(required = true)
    protected String provider;
    @XmlSchemaType(name = "anyURI")
    protected String rights;
    @XmlElement(required = true)
    protected Edmtype type;
    protected List<String> unstored;
    protected SimpleLiteral uri;
    protected List<SimpleLiteral> userTag;
    @XmlSchemaType(name = "date")
    protected List<XMLGregorianCalendar> year;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setCountry(SimpleLiteral value) {
        this.country = value;
    }

    /**
     * Gets the value of the dataProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProvider() {
        return dataProvider;
    }

    /**
     * Sets the value of the dataProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProvider(String value) {
        this.dataProvider = value;
    }

    /**
     * Gets the value of the hasMet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hasMet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasMet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    public List<SimpleLiteral> getHasMet() {
        if (hasMet == null) {
            hasMet = new ArrayList<SimpleLiteral>();
        }
        return this.hasMet;
    }

    /**
     * Gets the value of the hasType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hasType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    public List<SimpleLiteral> getHasType() {
        if (hasType == null) {
            hasType = new ArrayList<SimpleLiteral>();
        }
        return this.hasType;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setLanguage(SimpleLiteral value) {
        this.language = value;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObject(String value) {
        this.object = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the rights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRights() {
        return rights;
    }

    /**
     * Sets the value of the rights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRights(String value) {
        this.rights = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Edmtype }
     *     
     */
    public Edmtype getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Edmtype }
     *     
     */
    public void setType(Edmtype value) {
        this.type = value;
    }

    /**
     * Gets the value of the unstored property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unstored property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnstored().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUnstored() {
        if (unstored == null) {
            unstored = new ArrayList<String>();
        }
        return this.unstored;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setUri(SimpleLiteral value) {
        this.uri = value;
    }

    /**
     * Gets the value of the userTag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userTag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserTag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleLiteral }
     * 
     * 
     */
    public List<SimpleLiteral> getUserTag() {
        if (userTag == null) {
            userTag = new ArrayList<SimpleLiteral>();
        }
        return this.userTag;
    }

    /**
     * Gets the value of the year property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the year property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getYear().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getYear() {
        if (year == null) {
            year = new ArrayList<XMLGregorianCalendar>();
        }
        return this.year;
    }

}
