//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.04 at 01:49:42 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/EDMSchemaV9", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gr.ntua.ivml.mint.rdf.edm.types;
