//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.04 at 01:49:42 PM EEST 
//


package gr.ntua.ivml.mint.rdf.edm.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A Proxy is a Resource that indicates an Aggregated Resource in the context
 * of a specific Aggregation. The type ore:Proxy is associated with a Resource
 * via an assertion that describes the Aggregation that is the context of the
 * Proxy. The URI of a Proxy then can be used in assertions specific to the
 * Aggregated Resource in the context of that aggregation.
 * 
 * <p>Java class for ProxyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProxyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Europeana" type="{http://www.example.org/EDMSchemaV9}EuropeanaType"/>
 *         &lt;element name="DC" type="{http://www.example.org/EDMSchemaV9}DCType" minOccurs="0"/>
 *         &lt;element name="DCTerms" type="{http://www.example.org/EDMSchemaV9}DCTermsType" minOccurs="0"/>
 *         &lt;element name="EventWrap" type="{http://www.example.org/EDMSchemaV9}EventWrapType" minOccurs="0"/>
 *         &lt;element name="RelatedWrap" type="{http://www.example.org/EDMSchemaV9}RelatedProxiesWrapType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProxyType", propOrder = {
    "europeana",
    "dc",
    "dcTerms",
    "eventWrap",
    "relatedWrap"
})
public class ProxyType {

    @XmlElement(name = "Europeana", required = true)
    protected EuropeanaType europeana;
    @XmlElement(name = "DC")
    protected DCType dc;
    @XmlElement(name = "DCTerms")
    protected DCTermsType dcTerms;
    @XmlElement(name = "EventWrap")
    protected EventWrapType eventWrap;
    @XmlElement(name = "RelatedWrap")
    protected RelatedProxiesWrapType relatedWrap;

    /**
     * Gets the value of the europeana property.
     * 
     * @return
     *     possible object is
     *     {@link EuropeanaType }
     *     
     */
    public EuropeanaType getEuropeana() {
        return europeana;
    }

    /**
     * Sets the value of the europeana property.
     * 
     * @param value
     *     allowed object is
     *     {@link EuropeanaType }
     *     
     */
    public void setEuropeana(EuropeanaType value) {
        this.europeana = value;
    }

    /**
     * Gets the value of the dc property.
     * 
     * @return
     *     possible object is
     *     {@link DCType }
     *     
     */
    public DCType getDC() {
        return dc;
    }

    /**
     * Sets the value of the dc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCType }
     *     
     */
    public void setDC(DCType value) {
        this.dc = value;
    }

    /**
     * Gets the value of the dcTerms property.
     * 
     * @return
     *     possible object is
     *     {@link DCTermsType }
     *     
     */
    public DCTermsType getDCTerms() {
        return dcTerms;
    }

    /**
     * Sets the value of the dcTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCTermsType }
     *     
     */
    public void setDCTerms(DCTermsType value) {
        this.dcTerms = value;
    }

    /**
     * Gets the value of the eventWrap property.
     * 
     * @return
     *     possible object is
     *     {@link EventWrapType }
     *     
     */
    public EventWrapType getEventWrap() {
        return eventWrap;
    }

    /**
     * Sets the value of the eventWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventWrapType }
     *     
     */
    public void setEventWrap(EventWrapType value) {
        this.eventWrap = value;
    }

    /**
     * Gets the value of the relatedWrap property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedProxiesWrapType }
     *     
     */
    public RelatedProxiesWrapType getRelatedWrap() {
        return relatedWrap;
    }

    /**
     * Sets the value of the relatedWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedProxiesWrapType }
     *     
     */
    public void setRelatedWrap(RelatedProxiesWrapType value) {
        this.relatedWrap = value;
    }

}
