//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.04 at 01:49:42 PM EEST 
//


package gr.ntua.ivml.mint.rdf.edm.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				For every WebResourceType we make an instance of
 * 				edm:WebResource (WebResourceInst)
 * 
 * 				Relations EDMObjectInst edm:hasView WebResourceInst
 * 			
 * 
 * <p>Java class for WebResourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebResourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="isRepresentationOf" type="{http://www.example.org/EDMSchemaV9}PhysicalThingType" minOccurs="0"/>
 *         &lt;element name="isSimilarTo" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebResourceType", propOrder = {
    "resourceUri",
    "isRepresentationOf",
    "isSimilarTo"
})
public class WebResourceType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String resourceUri;
    protected PhysicalThingType isRepresentationOf;
    @XmlSchemaType(name = "anyURI")
    protected List<String> isSimilarTo;

    /**
     * Gets the value of the resourceUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceUri() {
        return resourceUri;
    }

    /**
     * Sets the value of the resourceUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceUri(String value) {
        this.resourceUri = value;
    }

    /**
     * Gets the value of the isRepresentationOf property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalThingType }
     *     
     */
    public PhysicalThingType getIsRepresentationOf() {
        return isRepresentationOf;
    }

    /**
     * Sets the value of the isRepresentationOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalThingType }
     *     
     */
    public void setIsRepresentationOf(PhysicalThingType value) {
        this.isRepresentationOf = value;
    }

    /**
     * Gets the value of the isSimilarTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isSimilarTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsSimilarTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIsSimilarTo() {
        if (isSimilarTo == null) {
            isSimilarTo = new ArrayList<String>();
        }
        return this.isSimilarTo;
    }

}
